question_data = [
    {
        "type": "boolean",
        "question": "A slug's blood is green.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "question": "The loudest animal is the African Elephant.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "question": "Approximately one quarter of human bones are in the feet.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "question": "The total surface area of a human lungs is the size of a football pitch.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "question": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "question": "A few ounces of chocolate can to kill a small dog.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "multiple",
        "difficulty": "medium",
        "category": "Sports",
        "question": "Which sport is NOT traditionally played during the Mongolian Naadam festival?",
        "correct_answer": "American Football",
        "incorrect_answers": ["Wrestling", "Archery", "Horse-Racing"],
    },
    {
        "type": "multiple",
        "difficulty": "medium",
        "category": "Entertainment: Video Games",
        "question": 'Which of these is not a character in the game,"Lethal League"',
        "correct_answer": "Rex",
        "incorrect_answers": ["Switch", "Candyman", "Sonata"],
    },
    {
        "type": "multiple",
        "difficulty": "medium",
        "category": "Entertainment: Comics",
        "question": "What's the weakness of american vampires (Scott Snyder's American Vampire)?",
        "correct_answer": "Gold",
        "incorrect_answers": ["Sunlight", "Wood", "Silver"],
    },
    {
        "type": "multiple",
        "difficulty": "medium",
        "category": "Entertainment: Japanese Anime &amp; Manga",
        "question": "In Haikyuu!!, who is not a member of Karasuno VBC?",
        "correct_answer": "Shigeru Yahaba",
        "incorrect_answers": [
            "Tadashi Yamaguchi",
            "Hisashi Kinoshita",
            "Kazuhito Narita",
        ],
    },
    {
        "type": "multiple",
        "difficulty": "medium",
        "category": "Geography",
        "question": "What is the highest mountain in the world?",
        "correct_answer": "Mt. Everest",
        "incorrect_answers": ["Mount Godwin Austen", "Kangchenjunga", "Annapurna"],
    },
    {
        "type": "multiple",
        "difficulty": "medium",
        "category": "Art",
        "question": "Which artist's studio was known as 'The Factory'",
        "correct_answer": "Andy Warhol",
        "incorrect_answers": ["Roy Lichtenstein", "David Hockney", "Peter Blake"],
    },
    {
        "type": "multiple",
        "difficulty": "medium",
        "category": "Entertainment: Books",
        "question": 'What was the name of the Mysterious Island, in Jules Verne\'s &"The Mysterious Island"',
        "correct_answer": "Lincoln Island",
        "incorrect_answers": ["Vulcania Island", "Prometheus Island", "Neptune Island"],
    },
    {
        "type": "multiple",
        "difficulty": "medium",
        "category": "Entertainment: Video Games",
        "question": "What is the world's first video game console?",
        "correct_answer": "Magnavox Odyssey",
        "incorrect_answers": ["Coleco Telstar", "Nintendo Color TV Game", "Atari 2600"],
    },
    {
        "type": "multiple",
        "difficulty": "medium",
        "category": "Geography",
        "question": "How many time zones are in Russia?",
        "correct_answer": "11",
        "incorrect_answers": ["8", "5", "2"],
    },
    {
        "type": "multiple",
        "difficulty": "medium",
        "category": "Entertainment: Video Games",
        "question": "Killing Floor started as a mod for which Unreal Engine 2 game?",
        "correct_answer": "Unreal Tournament 2004",
        "incorrect_answers": [
            "Deus Ex: Invisible War",
            "Unreal Tournament 3",
            "Postal",
        ],
    },
    {
        "type": "multiple",
        "difficulty": "hard",
        "category": "Science: Mathematics",
        "question": 'What is the fourth digit of "pi"',
        "correct_answer": "1",
        "incorrect_answers": ["2", "3", "4"],
    },
    {
        "type": "multiple",
        "difficulty": "medium",
        "category": "Science: Mathematics",
        "question": "How many zeros are there in a googol?",
        "correct_answer": "100",
        "incorrect_answers": ["10", "1,000", "1,000,000"],
    },
    {
        "type": "multiple",
        "difficulty": "hard",
        "category": "Science: Mathematics",
        "question": "What is the derivative of Acceleration with respect to time?",
        "correct_answer": "Jerk",
        "incorrect_answers": ["Shift", "Bump", "Slide"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Mathematics",
        "question": "The sum of any two odd integers is odd.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Science: Mathematics",
        "question": "111,111,111 x 111,111,111 = 12,345,678,987,654,321",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Science: Mathematics",
        "question": "What's the square root of 49?",
        "correct_answer": "7",
        "incorrect_answers": ["4", "12", "9"],
    },
    {
        "type": "multiple",
        "difficulty": "hard",
        "category": "Science: Mathematics",
        "question": "Which of the following famous mathematicians died in a duel at the age of 20?",
        "correct_answer": "Galois",
        "incorrect_answers": ["Abel", "Euler", "Gauss"],
    },
    {
        "type": "multiple",
        "difficulty": "hard",
        "category": "Science: Mathematics",
        "question": "The French mathematician &Eacute;variste Galois is primarily known for his work in which?",
        "correct_answer": "Galois Theory",
        "incorrect_answers": [
            "Galois Continued Fractions",
            "Galois Method for PDE&#039;s ",
            "Abelian Integration",
        ],
    },
    {
        "type": "boolean",
        "difficulty": "hard",
        "category": "Science: Mathematics",
        "question": "In Topology, the complement of an open set is a closed set.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "multiple",
        "difficulty": "hard",
        "category": "Science: Mathematics",
        "question": "What is the smallest number that can be expressed as the sum of two positive cubes in two different ways?",
        "correct_answer": "1729",
        "incorrect_answers": ["91", "561", "4104"],
    },
    {
        "type": "multiple",
        "difficulty": "medium",
        "category": "Science: Computers",
        "question": "Which programming language was developed by Sun Microsystems in 1995?",
        "correct_answer": "Java",
        "incorrect_answers": ["Python", "Solaris OS", "C++"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "multiple",
        "difficulty": "medium",
        "category": "Science: Computers",
        "question": "What does AD stand for in relation to Windows Operating Systems? ",
        "correct_answer": "Active Directory",
        "incorrect_answers": [
            "Alternative Drive",
            "Automated Database",
            "Active Department",
        ],
    },
    {
        "type": "multiple",
        "difficulty": "hard",
        "category": "Science: Computers",
        "question": "Which data structure does FILO apply to?",
        "correct_answer": "Stack",
        "incorrect_answers": ["Queue", "Heap", "Tree"],
    },
    {
        "type": "multiple",
        "difficulty": "medium",
        "category": "Science: Computers",
        "question": 'In the programming language "Python", which of these statements would display the string "Hello World" correctly?',
        "correct_answer": 'print("Hello World")',
        "incorrect_answers": [
            'console.log("Hello World&quot")',
            'echo "Hello World"',
            'printf("Hello World")',
        ],
    },
    {
        "type": "multiple",
        "difficulty": "hard",
        "category": "Science: Computers",
        "question": "Who is the founder of Palantir?",
        "correct_answer": "Peter Thiel",
        "incorrect_answers": ["Mark Zuckerberg", "Marc Benioff", "Jack Dorsey"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Science: Computers",
        "question": "Android versions are named in alphabetical order.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "multiple",
        "difficulty": "medium",
        "category": "Science: Computers",
        "question": 'When was the programming language "C#" released?',
        "correct_answer": "2000",
        "incorrect_answers": ["1998", "1999", "2001"],
    },
    {
        "type": "multiple",
        "difficulty": "medium",
        "category": "Science: Computers",
        "question": "Nvidia's headquarters are based in which Silicon Valley city?",
        "correct_answer": "Santa Clara",
        "incorrect_answers": ["Palo Alto", "Cupertino", "Mountain View"],
    },
    {
        "type": "multiple",
        "difficulty": "medium",
        "category": "Science: Computers",
        "question": "What is the number of keys on a standard Windows Keyboard?",
        "correct_answer": "104",
        "incorrect_answers": ["64", "94", "76"],
    },
]
